[build-system]
requires = [
    "scikit_build_core",
    "pybind11",
]
build-backend = "scikit_build_core.build"

[project]
name = "mvhg"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = [
    "numpy"
]

[project.optional-dependencies]
test = ["pytest>=6.0"]